# ============================================
# Configuracion de Eclipse Mosquitto
# Sistema de Monitoreo de Flota Logistica
# ============================================

# Listener principal MQTT
listener 1883
protocol mqtt

# Listener WebSocket (para dashboard web)
listener 9001
protocol websockets

# Permitir conexiones anonimas (desarrollo)
allow_anonymous true

# Persistencia de mensajes
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type all
